,(import (rename (except (srfi 144)
                          fl-integer-exponent-zero
                          fl-integer-exponent-nan
			  flmax flmin)
		  (fl+ srfi-144:fl+)
		  (fl- srfi-144:fl-)
		  (fl/ srfi-144:fl/)
		  (fl* srfi-144:fl*)
		  (fllog1+ fllog+1)
		  (flonum srfi-144:flonum)
                  (flsign-bit srfi-144:flsign-bit)
                  (flinteger-exponent srfi-144:flinteger-exponent)
		  (flquotient fltruncate-quotient)
		  (flremainder fltruncate-remainder)
                  (flnormalized? flnormal?)
                  (fldenormalized? flsubnormal?)))
,(import (rename (only (srfi 143) fx-greatest fx-least)
                     (fx-greatest large-positive-integer)
                     (fx-least large-negative-integer)))

;;;; NOTE: This test suite assumes round toward nearest behavior.

(load "tests/tests.mit-scheme.scm")
(load "tests/random-flonum.scm")
(load "lib/srfi/276.utils.scm")

(load "lib/srfi/276.sign-negative.scm")
(load "tests/flsign-negative.scm")
(test-flsign-negative?)

(load "lib/srfi/276.integer-exponent.scm")
(load "lib/srfi/276.new-constants.scm")
(load "tests/flinteger-exponent.scm")
(test-flinteger-exponent)

(load "tests/implementation-constants.scm")
(begin
  (test-fl-radix)
  (test-fl-precision)
  (test-fl-maximum-exponent)
  (test-fl-minimum-exponent)
  (test-fl-minimum-normalized-exponent)
  (test-fl-limit-constants)
  (test-fl-epsilon)
  (test-fl-byte-width))

(load "lib/srfi/276.serialization.scm")
(load "tests/bytevector.scm")
(test-binary64-bytevector-on-basic-numbers)
(test-binary64-bytevector-flonum-ref)
(test-bytevector-flonum-native-reverse)
(test-bytevector-flonum-reverse)

(load "lib/srfi/276.flonum.scm")
(load "tests/flonum.scm")
(test-flonum)
(test-flonum-property)

(load "tests/fladjacent.scm")
(test-fladjacent)

(load "tests/flcopysign.scm")
(test-flcopysign)

(load "tests/flinteger-fraction.scm")
(test-flinteger-fraction)

(load "tests/flexponent.scm")
(test-flexponent)

(load "tests/flnormalized-fraction-exponent.scm")
(test-flnormalized-fraction-exponent)
(flnormalized-fraction-exponent-and-make-flonum-are-inverses)
(load "tests/make-flonum.scm")
(test-make-flonum)

(load "lib/srfi/276.fl-not-equal.scm")
(load "lib/srfi/276.total.scm")
(load "tests/order.scm")
(test-flonum-order)
(test-negative-infinity-less-than-all-ordered)
(test-fl-greatest-is-greater-than-all-finite)
(test-positive-infinity-is-greater-than-all-ordered)
(test-trichotomy-of-order)
(test-weak-order)

(load "tests/total-order.scm")
(test-fl<?-implies-fltotal<?)
(test-eqv?-implies-fltotal=?)
(test-trichotomy-of-total-order)
(test-weak-total-order)
(test-nans-are-ordered-beyond-finite-values)
(test-total-order-special-cases)

(load "lib/srfi/276.flordered.scm")
(load "tests/flunordered.scm")
(test-nans-are-unordered)
(test-non-nans-are-ordered)

(load "lib/srfi/276.fl-not-equal.scm")
(load "tests/fl-not-equal.scm")
(test-fl!=?)

(load "tests/subtype-predicates.scm")
(test-flinteger?)
(test-flzero?)
(test-flpositive?)
(test-flnegative?)
(test-flodd?)
(test-fleven?)
(test-flfinite?)
(test-flinfinite?)
(test-property-nans)
(test-flnormal?)
(test-flsubnormal?)

(load "lib/srfi/276.maxmin.scm")
(load "tests/maxmin.scm")
(test-flmax)
(test-flmax-filter-nans)
(test-flmin)
(test-flmin-filter-nans)
(test-flmax-abs)
(test-flmax-abs-filter-nans)
(test-flmin-abs)
(test-flmin-abs-filter-nans)

(load "lib/srfi/276.arith.scm")
(load "tests/arith.scm")
(test-fl+)
(test-fl-)
(test-fl*)
(test-fl/)

(load "tests/fma.scm")
(test-fl+*)

(load "tests/abs.scm")
(test-flabs)
(test-flabs-sign-positive)

(load "tests/flabsdiff.scm")
(test-flabsdiff)
(test-flabsdiff-defining-property)

(load "tests/flposdiff.scm")
(test-flposdiff)
(test-flabsdiff-defining-property)

(load "tests/flsgn.scm")
(test-flsgn-defining-property)

(load "tests/flnumerator-and-fldenominator.scm")
(test-flnumerator)
(test-fldenominator)
(test-flnumerator-and-fldenominator-property)

(load "tests/flfloor.scm")
(test-flfloor)
(test-flfloor-is-integer)
(test-flfloor-not-larger)

(load "tests/flceiling.scm")
(test-flceiling)
(test-flceiling-is-integer)
(test-flceiling-not-smaller)

(load "tests/fltruncate.scm")
(test-fltruncate)
(test-fltruncate-is-integer)
(test-fltruncate-closer-to-zero)

(load "tests/flround.scm")
(test-flround)
(test-flround-is-integer)
(test-flround-property)

(load "lib/srfi/276.round-away.scm")
(load "tests/flround-away.scm")
(test-flround-away)
(test-flround-away-is-integer)
(test-flround-away-property)

(load "tests/fltruncate-quotient.scm")
(test-fltruncate-quotient-for-infinite-denominator)
(test-fltruncate-quotient-finite-sign)

(load "tests/test-flremquo.scm")
(test-flremquo)

(load "lib/srfi/276.exp.scm")
(load "tests/flexp.scm")
(test-flexp)
(test-flexp-1)
(test-flexp2)
(test-flexp2-1)
(test-flexp10)
(test-flexp10-1)
(test-flexpt-to-the-power-of-zero)
(test-flexpt-0.0-negative-odd)
(test-flexpt-0.0-negative-not-odd)
(test-flexpt-finite-non-integer)
(test-flexpt-special-cases)
(test-flexpt-0.0-positive-odd)
(test-flexpt-0.0-positive-non-odd)
(test-flexpt-1.0-power)
(test-flexpt-below-unity-to-infinity)
(test-flexpt-below-unity-for-minus-infinity)
(test-flexpt-above-unity-for-infinity)
(test-flexpt-above-unity-for-minus-infinity)
(test-flexpt-infinity-to-negative)
(test-flexpt-infinity-to-positive)
(test-flexpt-minus-infinity-to-positive-odd)
(test-flexpt-minus-infinity-to-negative-odd)
(test-flexpt-minus-infinity-to-positive-non-odd)
(test-flexpt-minus-infinity-to-negative-non-odd)
(test-flexpt-nan-rules)

(load "lib/srfi/276.fllog.scm")
(load "tests/fllog.scm")

(test-fllog)
(test-fllog2)
(test-fllog10)
(test-fllog+1)
(test-fllog2+1)
(test-fllog10+1)

(load "lib/srfi/276.cbrt.scm")
(load "tests/flcbrt.scm")
(test-flcbrt)

(load "lib/srfi/276.compound.scm")
(load "tests/flcompound.scm")
(test-flcompound-to-zero)
(test-flcompound-below-zero)
(test-flcompound-minus-1-to-negative)
(test-flcompound-minus-1-to-positive)
(test-flcompound-infinite-to-positive)
(test-flcompound-infinite-to-negative)
(test-flcompound-nan)

(load "tests/flhypot.scm")
(test-flhypot)
(test-flhypot-0.0)
(test-flhypot-0.0-symmetric)
(test-flhypot-inf.0)
(test-flhypot-inf.0-symmetric)

(load "lib/srfi/276.rsqrt.scm")
(load "tests/flrsqrt.scm")
(test-flrsqrt)

(load "tests/flsqrt.scm")
(test-flsqrt)

(load "tests/fltrig.scm")
(test-flsin)
(test-flsin-odd-property)
(test-flcos)
(test-flcos-even-property)
(test-fltan)
(test-fltan-odd-property)

(load "lib/srfi/276.trigpi.scm")
(load "tests/fltrigpi.scm")
(test-flsinpi)
(test-flsinpi-odd)
(test-flsinpi-integer-property)

(test-flcospi)
(test-flcospi-even)
(test-flcospi-half-integer)

(test-fltanpi)
(test-fltanpi-odd)
(test-fltanpi-positive-even-integers)
(test-fltanpi-negative-odd-integers)
(test-fltanpi-on-positive-odd-integers)
(test-fltanpi-on-negative-even-integers)
(test-fltanpi-on-positive-even-integer+0.5)
(test-fltanpi-on-negative-odd-integer-0.5)
(test-fltanpi-on-positive-odd-integer+0.5)
(test-fltanpi-on-negative-even-integer-0.5)

(load "tests/flinverse-trig.scm")
(test-flasin)
(test-flasin-is-odd)
(test-flasin-inversion)

(test-flacos)
(test-flacos-inversion)

(test-flatan)
(test-flatan-odd)
(test-flatan-zero-y)
(test-flatan-first-quadrant)
(test-flatan-positive-y-zero-x)
(test-flatan-positive-y-negative-x)
(test-flatan-zero-y-negative-x)
(test-flatan-negative-y-negative-x)
(test-flatan-negative-y-zero-x)
(test-flatan-negative-y-positive-x)
(test-flatan-x=-inf.0)
(test-flatan-x=+inf.0)
(test-flatan-y-infinite-x-finite)

(load "lib/srfi/276.flinverse-trigpi.scm")
(test-flasinpi)
(test-flasinpi-is-odd)
(test-flasinpi-inversion)

(test-flacospi)
(test-flacospi-inversion)

(test-flatanpi)
(test-flatanpi-odd)
(test-flatanpi-zero-y)
(test-flatanpi-first-quadrant)
(test-flatanpi-positive-y-zero-x)
(test-flatanpi-positive-y-negative-x)
(test-flatanpi-zero-y-negative-x)
(test-flatanpi-negative-y-negative-x)
(test-flatanpi-negative-y-zero-x)
(test-flatanpi-negative-y-positive-x)
(test-flatanpi-x=-inf.0)
(test-flatanpi-x=+inf.0)
(test-flatanpi-y-infinite-x-finite)

(load "tests/flhyp.scm")
(test-flsinh)
(test-flsinh-odd)
(test-flcosh)
(test-flcosh-even)
(test-fltanh)
(test-fltanh-odd)

(test-flasinh)
(test-flasinh-odd)
(test-flacosh)
(test-flacosh-below-one)
(test-flatanh)
(test-flatanh-nan)
(test-flatanh-odd)

(load "tests/special-functions.scm")
(test-flerf)
(test-flerf-odd)
(test-flerfc)
(test-flgamma)
(test-flgamma-on-negative-integers)
(test-flloggamma)
(test-flloggamma-on-negative-integers)

;;; FIXME: No tests for bessel functions yet


