(define (fltruncate-remainder x y)
  (let ((ax (flabs x))
        (ay (flabs y)))
    (cond
      ((or (flzero? y) (not (flfinite? x)) (flnan? y))
       (fl/ (fl* x y) (fl* x y)))
      ((fl=? ax ay) (flcopysign 0.0 ax))
      ((fl<? ax ay)
       ;; truncate(|x/y|) = 0, so r = x.
       ax)
      (else (fltruncate-remainder* x y)))))

(define (fltruncate-remainder* x y)
  (let*-values (((fx ex) (flnormalized-fraction-exponent x))
                ((fy ey) (flnormalized-fraction-exponent y))
                ((ix) (exact (make-flonum fx fl-precision)))
                ((iy) (exact (make-flonum fy fl-precision)))
                ((r) (truncate-remainder ix iy))
                ((adjustment-sign) (cond
                                     ((and (negative? r) (positive? iy))
                                      (flonum -1.0))
                                     ((and (positive? r) (negative? iy))
                                      (flonum -1.0))
                                     ((and (positive? r) (positive? iy))
                                      (flonum 1.0))
                                     ((and (negative? r) (negative? iy))
                                      (flonum 1.0)))))
    (if (zero? r)
        (flonum r)
        (do ((n 0 (+ n 1))
             (r r (let ((r (* r 2)))
                    (if (>= (abs r) (abs iy))
                        (- r (* adjustment-sign iy))
                        r))))
            ((= n (- ex ey))
             (make-flonum (flonum r) (- ey fl-precision)))))))
