(define (test-flinteger-exponent)
  (test-group "flinteger-exponent"
    (test-values (flinteger-exponent 1.0) '(0))
    (test-values (flinteger-exponent 2.0) '(1))
    (test-values (flinteger-exponent 4.0) '(2))
    (test-values (flinteger-exponent +nan.0) `(,fl-integer-exponent-nan))
    (test-values (flinteger-exponent +0.0) `(,fl-integer-exponent-zero))
    (test-values (flinteger-exponent -0.0) `(,fl-integer-exponent-zero)))
    (test-values (> (flinteger-exponent +inf.0)
                    fl-maximum-exponent)
                 '(#t))
    (test-values (> (flinteger-exponent -inf.0)
                    fl-maximum-exponent)
                 '(#t)))
