(define (test-flinteger-fraction)
  (test-values (flinteger-fraction (flonum 1.0))
	       (list (flonum 1.0) (flonum 0.0)))
  (test-values (flinteger-fraction (flonum -1.0))
	       (list (flonum -1.0) (flonum -0.0)))
  (test-values (flinteger-fraction (flonum -1.5))
	       (list (flonum -1.0) (flonum -0.5)))
  (test-values (flinteger-fraction (flonum 1.5))
	       (list (flonum 1.0) (flonum 0.5)))
  (test-values (flinteger-fraction (flonum +inf.0))
	       (list (flonum +inf.0) (flonum 0.0)))
  (test-values (flinteger-fraction (flonum -inf.0))
	       (list (flonum -inf.0) (flonum -0.0)))
  (test-values (flinteger-fraction (flonum 0.5))
	       (list (flonum 0.0) (flonum 0.5)))
  (test-values (flinteger-fraction (flonum -0.5))
	       (list (flonum -0.0) (flonum -0.5)))
  (test-assert (let-values (((i f) (flinteger-fraction (flonum +nan.0))))
		 (and (flnan? i) (flnan? f)))))

(define (test-flinteger-fraction-summation-property)
  (test-property "(flinteger-fraction fl) => (i d) --> (fl+ i d) = fl"
                 random-flonum
		 (lambda (flonum)
		   (when (flfinite? flonum)
		     (let-values (((i d) (flinteger-fraction flonum)))
		       (test-assert (fl=? (fl+ i d) flonum)))))))
