(define (test-make-flonum)
  (test-values (make-flonum 1.0 0)
	       '(1.0))
  (test-values (make-flonum 0.5 2)
	       '(2.0))
  (test-values (make-flonum fl-greatest 1)
	       '(+inf.0))
  (test-values (make-flonum (fl- fl-greatest) 1)
	       '(-inf.0))
  (test-values (make-flonum fl-least -1)
	       '(0.0))
  (test-values (make-flonum (fl- fl-least) -1)
	       '(-0.0)))
