(import (scheme base) (srfi 27) (srfi 276) (srfi 64) (srfi 194) (srfi 252) (srfi 158))

(define skipping? #f)

(test-begin "SRFI 276")
(cond-expand
  ((not gambit)
   (test-skip (lambda ignored skipping?)))
  (else))

(include "tests.srfi-64.scm")
(include "random-flonum.scm")

(include "flsign-negative.scm")
(test-flsign-negative?)

(include "flinteger-exponent.scm")
(test-flinteger-exponent)

(include "implementation-constants.scm")
(begin
  (test-fl-radix)
  (test-fl-precision)
  (test-fl-maximum-exponent)
  (test-fl-minimum-exponent)
  (test-fl-minimum-normalized-exponent)
  (test-fl-limit-constants)
  (test-fl-epsilon)
  (test-fl-byte-width))

(include "bytevector.scm")
(test-binary64-bytevector-on-basic-numbers)
(test-binary64-bytevector-flonum-ref)
(test-bytevector-flonum-native-reverse)
(test-bytevector-flonum-reverse)

(include "flonum.scm")
(test-flonum)
(test-flonum-property)

(include "fladjacent.scm")
(test-fladjacent)

(include "flcopysign.scm")
(test-flcopysign)

(include "flinteger-fraction.scm")
(test-flinteger-fraction)

(include "flexponent.scm")
(test-flexponent)

(include "flnormalized-fraction-exponent.scm")
(test-flnormalized-fraction-exponent)
(flnormalized-fraction-exponent-and-make-flonum-are-inverses)

(include "order.scm")
(test-flonum-order)
(test-negative-infinity-less-than-all-ordered)
(test-fl-greatest-is-greater-than-all-finite)
(test-positive-infinity-is-greater-than-all-ordered)
(test-trichotomy-of-order)
(test-weak-order)

(include "total-order.scm")
(test-fl<?-implies-fltotal<?)
(test-eqv?-implies-fltotal=?)
(test-trichotomy-of-total-order)
(test-weak-total-order)
(test-nans-are-ordered-beyond-finite-values)
(test-total-order-special-cases)

(include "flunordered.scm")
(test-nans-are-unordered)
(test-non-nans-are-ordered)

(include "fl-not-equal.scm")
(test-fl!=?)

(include "subtype-predicates.scm")
(test-flinteger?)
(test-flzero?)
(test-flpositive?)
(test-flnegative?)
(test-flodd?)
(test-fleven?)
(test-flfinite?)
(test-flinfinite?)
(test-property-nans)
(test-flnormal?)
(test-flsubnormal?)

(include "maxmin.scm")
(test-flmax)
(test-flmax-filter-nans)
(test-flmin)
(test-flmin-filter-nans)
(test-flmax-abs)
(test-flmax-abs-filter-nans)
(test-flmin-abs)
(test-flmin-abs-filter-nans)

(include "arith.scm")
(test-fl+)
(test-fl-)
(test-fl*)
(test-fl/)

(include "fma.scm")
(test-fl+*)

(include "abs.scm")
(test-flabs)
(test-flabs-sign-positive)

(include "flabsdiff.scm")
(test-flabsdiff)
(test-flabsdiff-defining-property)

(include "flposdiff.scm")
(test-flposdiff)
(test-flabsdiff-defining-property)

(include "flsgn.scm")
(test-flsgn-defining-property)

(include "flnumerator-and-fldenominator.scm")
(test-flnumerator)
(test-fldenominator)
(test-flnumerator-and-fldenominator-property)

(include "flfloor.scm")
(test-flfloor)
(test-flfloor-is-integer)
(test-flfloor-not-larger)

(include "flceiling.scm")
(test-flceiling)
(test-flceiling-is-integer)
(test-flceiling-not-smaller)

(include "fltruncate.scm")
(test-fltruncate)
(test-fltruncate-is-integer)
(test-fltruncate-closer-to-zero)

(include "flround.scm")
(test-flround)
(test-flround-is-integer)
(test-flround-property)

(include "flround-away.scm")
(test-flround-away)
(test-flround-away-is-integer)
(test-flround-away-property)

(include "fltruncate-quotient.scm")
(test-fltruncate-quotient-for-infinite-denominator)
(test-fltruncate-quotient-finite-sign)

(include "test-flremquo.scm")
(test-flremquo)

(include "flexp.scm")
(test-flexp)
(test-flexp-1)
(test-flexp2)
(test-flexp2-1)
(test-flexp10)
(test-flexp10-1)
;; Gauche's flexpt returns complex numbers instead of NaNs.
(cond-expand
  (gauche (set! skipping? #t))
  (else))
(test-flexpt-to-the-power-of-zero)
(test-flexpt-0.0-negative-odd)
(test-flexpt-0.0-negative-not-odd)
(test-flexpt-finite-non-integer)
(test-flexpt-special-cases)
(test-flexpt-0.0-positive-odd)
(test-flexpt-0.0-positive-non-odd)
(test-flexpt-1.0-power)
(test-flexpt-below-unity-to-infinity)
(test-flexpt-below-unity-for-minus-infinity)
(test-flexpt-above-unity-for-infinity)
(test-flexpt-above-unity-for-minus-infinity)
(test-flexpt-infinity-to-negative)
(test-flexpt-infinity-to-positive)
(test-flexpt-minus-infinity-to-positive-odd)
(test-flexpt-minus-infinity-to-negative-odd)
(test-flexpt-minus-infinity-to-positive-non-odd)
(test-flexpt-minus-infinity-to-negative-non-odd)
(test-flexpt-nan-rules)
(cond-expand
  (gauche (set! skipping? #f))
  (else))

(include "fllog.scm")

(test-fllog)
(test-fllog2)
(test-fllog10)
(test-fllog+1)
(test-fllog2+1)
(test-fllog10+1)

(include "flcbrt.scm")
(test-flcbrt)

(include "flcompound.scm")
(test-flcompound-to-zero)
(test-flcompound-below-zero)
(test-flcompound-minus-1-to-negative)
(test-flcompound-minus-1-to-positive)
(test-flcompound-infinite-to-positive)
(test-flcompound-infinite-to-negative)
(test-flcompound-nan)

(include "flhypot.scm")
(test-flhypot)
(test-flhypot-0.0)
(test-flhypot-0.0-symmetric)
(test-flhypot-inf.0)
(test-flhypot-inf.0-symmetric)


(include "flrsqrt.scm")
(test-flrsqrt)

(include "flsqrt.scm")
(test-flsqrt)

(include "fltrig.scm")
(test-flsin)
(test-flsin-odd-property)
(test-flcos)
(test-flcos-even-property)
(test-fltan)
(test-fltan-odd-property)

(include "fltrigpi.scm")
(test-flsinpi)
(test-flsinpi-odd)
(test-flsinpi-integer-property)

(test-flcospi)
(test-flcospi-even)
(test-flcospi-half-integer)

(test-fltanpi)
(test-fltanpi-odd)
(test-fltanpi-positive-even-integers)
(test-fltanpi-on-negative-odd-integers)
(test-fltanpi-on-positive-odd-integers)
(test-fltanpi-on-negative-even-integers)
(test-fltanpi-on-positive-even-integer+0.5)
(test-fltanpi-on-negative-odd-integer-0.5)
(test-fltanpi-on-positive-odd-integer+0.5)
(test-fltanpi-on-negative-even-integer-0.5)

(include "flinverse-trig.scm")
(test-flasin)
(test-flasin-is-odd)
(test-flasin-inversion)

(test-flacos)
(test-flacos-inversion)

(test-flatan)
(test-flatan-odd)
(test-flatan-zero-y)
(test-flatan-first-quadrant)
(test-flatan-positive-y-zero-x)
(test-flatan-positive-y-negative-x)
(test-flatan-zero-y-negative-x)
(test-flatan-negative-y-negative-x)
(test-flatan-negative-y-zero-x)
(test-flatan-negative-y-positive-x)
(test-flatan-x=-inf.0)
(test-flatan-x=+inf.0)
(test-flatan-y-infinite-x-finite)

(include "flinverse-trigpi.scm")
(test-flasinpi)
(test-flasinpi-is-odd)
(test-flasinpi-inversion)

(test-flacospi)
(test-flacospi-inversion)

(test-flatanpi)
(test-flatanpi-odd)
(test-flatanpi-zero-y)
(test-flatanpi-first-quadrant)
(test-flatanpi-positive-y-zero-x)
(test-flatanpi-positive-y-negative-x)
(test-flatanpi-zero-y-negative-x)
(test-flatanpi-negative-y-negative-x)
(test-flatanpi-negative-y-zero-x)
(test-flatanpi-negative-y-positive-x)
(test-flatanpi-x=-inf.0)
(test-flatanpi-x=+inf.0)
(test-flatanpi-y-infinite-x-finite)

(include "flhyp.scm")
(test-flsinh)
(test-flsinh-odd)
(test-flcosh)
(test-flcosh-even)
(test-fltanh)
(test-fltanh-odd)

(test-flasinh)
(test-flasinh-odd)
(test-flacosh)
(test-flacosh-below-one)
(test-flatanh)
(test-flatanh-nan)
(test-flatanh-odd)

(include "special-functions.scm")
(test-flerf)
(test-flerf-odd)
(test-flerfc)
(test-flgamma)
(test-flgamma-on-negative-integers)
(test-flloggamma)
(test-flloggamma-on-negative-integers)

;;; FIXME: No tests for bessel functions yet

(test-end "SRFI 276")
